apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
spec:
  selector:
    matchLabels:
      stack: backend
      app: gateway
  template:
    metadata:
      labels:
        stack: backend
        app: gateway
    spec:
      containers:
      - name: gateway
        image: mdarmawan/gateway:mdtest # TODO: Placeholder
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env: 
        - name: spring.cloud.consul.discovery.hostname
          value: quiz-svc
        envFrom:
        - configMapRef:
            name: consul-connection

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  annotations:
    'consul.hashicorp.com/service-sync': 'true'
spec:
  type: LoadBalancer #to expose to outside the cluster easier in AKS
  selector:
    stack: backend
    app: gateway
  ports:
  - port: 8080
    name: entrypoint
