apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: backend
      app: quiz
  template:
    metadata:
      labels:
        stack: backend
        app: quiz
    spec:
      containers:
      - name: quiz
        image: mdarmawan/quiz:mdtest # TODO: Placeholder
        resources:
          limits:
            memory: "1.5Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8090
        volumeMounts: [] # Placeholder
        env: 
        - name: spring.cloud.consul.discovery.hostname
          value: quiz-svc
        envFrom:
        - configMapRef:
            name: consul-connection
        # - configMapRef:
        #     name: db-info
      volumes: [] # Placeholder

---
apiVersion: v1
kind: Service
metadata:
  name: quiz-svc
  # annotations:
  #   'consul.hashicorp.com/service-sync': 'true'
spec:
  type: ClusterIP
  selector:
    stack: backend
    app: quiz
  ports:
  - port: 8090
    name: quiz-port
