apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.mynamespace }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    stack: backend
    app: gateway
  ports:
  - port: {{ .Values.gateway.port }}
    name: {{ .Values.gateway.service.portName }}
