{{- if or .Values.deployAll .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment # maybe kafka should be stateful in case of interruption of messaging
metadata:
  name: kafka-deploy
spec:
  {{- with .Values.kafka }}
  selector:
    matchLabels:
      {{- include "testchart.selectorLabels" . | nindent 6 }}
      stack: dependency
      app: kafka
  template:
    metadata:
      labels:
        {{- include "testchart.selectorLabels" . | nindent 8 }}
        stack: dependency
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:{{ .deploy.imageTag }}
        ports:
        - containerPort: {{ .port }}
        {{- with .deploy.resources }}
        resources:
          limits:
            memory: {{ .limits.memory | quote }}
            cpu: {{ .limits.cpu | quote }}
        {{- end }}
  {{- end }}
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: {{ .Values.zookeeper.service.name }}:{{ .Values.zookeeper.port }}
{{- end }}