{{- if or .Values.deployAll .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.service.name }}
spec:
  {{- with .Values.kafka }}
  selector:
    stack: dependency
    app: kafka
  type: {{ .service.type }}
  ports:
  - port: {{ .port }}
    name: {{ .service.ports.name }}
  {{- end }}
{{- end }}