{{- if or .Values.deployAll .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment # maybe zookeeper should be a statefulSet
metadata:
  name: {{ .Values.zookeeper.deploy.name }}
spec:
  {{- with .Values.zookeeper }}
  selector:
    matchLabels:
      stack: dependency
      app: zoo
      {{- include "testchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "testchart.selectorLabels" . | nindent 8 }}
        stack: dependency
        app: zoo
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:{{ .deploy.imageTag }}
        ports: 
        - containerPort: {{ .port }}
        env:
        - name: ALLOW_ANONYMOUS_LOGIN #hard-coding here is fine, I think.
          value: "yes"
        {{- with .deploy.resources }}
        resources:
          limits:
            memory: {{ .limits.memory | quote }}
            cpu: {{ .limits.cpu | quote }}
        {{- end }}
  {{- end }}
{{- end }}