version: "3"
services:
  flashcard:
    build:
      context: .
      dockerfile: flashcard.Dockerfile
  quiz:
    build:
      context: .
      dockerfile: quiz.Dockerfile
  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
