version: "3"
services:
  flashcard:
    build:
      context: .
      dockerfile: flashcard.Dockerfile
    ports:
      - 8089:8089
    environment: 
      spring.kafka.consumer.bootstrap-servers: kafka:9092
      spring.kafka.producer.bootstrap-servers: kafka:9092
      spring.cloud.consul.host: consul
      spring.cloud.consul.port: 8500
    depends_on: 
      - consul
      - kafka
  quiz:
    build:
      context: .
      dockerfile: quiz.Dockerfile
    ports:
      - 8090:8090
    environment: 
      spring.cloud.consul.host: consul
      spring.cloud.consul.port: 8500
      spring.cloud.config.enabled: "false"
    depends_on: 
      - consul
  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    ports:
      - 5000:8080
    environment: 
      spring.cloud.consul.host: consul
      spring.cloud.consul.port: 8500
    depends_on: 
      - consul
  consul:
    image: consul
    ports:
      - 8500:8500
    logging:
      driver: "none"
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    logging:
      driver: "none"
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    logging:
      driver: "none"