version: "3"
services:
  flashcard:
    build:
      context: .
      dockerfile: flashcard.Dockerfile
    ports:
      - 8089:8089
    depends_on: 
      - consul
      - kafka
  quiz:
    build:
      context: .
      dockerfile: quiz.Dockerfile
    ports:
      - 8090:8090
    depends_on: 
      - consul
  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    ports:
      - 5000:8080
    depends_on: 
      - consul
  consul:
    image: consul
    ports:
      - 8500:8500
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper