apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fcdb-pvc
spec:
  storageClassName: default
  resources:
    requests:
      storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce