apiVersion: apps/v1
kind: Deployment # maybe zookeeper should be a statefulSet
metadata:
  name: consul-deploy
  namespace: p2t4 # in theory, this is inadvisable to put here, use kubectl
spec:
  selector:
    stack: dependency
    app: consul
  template:
    metadata:
      labels:
        stack: dependency
        app: consul
    spec:
      containers:
      - name: consul
        image: consul
        ports: 
        - containerPort: 8500
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: consul-svc
  namespace: p2t4
spec:
  selector:
    stack: dependency
    app: consul
  type: ClusterIP
  ports:
    - 2181
