apiVersion: apps/v1
kind: Deployment # maybe zookeeper should be a statefulSet
metadata:
  name: consul-deploy
spec:
  selector:
    matchLabels:
      stack: dependency
      app: consul
  template:
    metadata:
      labels:
        stack: dependency
        app: consul
    spec:
      containers:
      - name: consul
        image: consul
        ports: 
        - containerPort: 8500
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: consul-svc
spec:
  selector:
    stack: dependency
    app: consul
  type: ClusterIP
  ports:
  - port: 8500
    name: consul-svc-port
