apiVersion: apps/v1
kind: Deployment # maybe zookeeper should be a statefulSet
metadata:
  name: zookeeper-deploy
spec:
  selector:
    matchLabels:
      stack: dependency
      app: zoo
  template:
    metadata:
      labels:
        stack: dependency
        app: zoo
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper
        ports: 
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN #hard-coding here is fine, I think.
          value: "yes"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
spec:
  selector:
    stack: dependency
    app: zoo
  type: ClusterIP
  ports:
    - port: 2181
