# This is a basic workflow to help you get started with Actions

name: GithubActionsTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Discord Message Notify
        # You may pin to the exact commit or the version.
        # uses: appleboy/discord-action@4c196125180125310ac20c72034757bb71020383
        uses: appleboy/discord-action@0.0.3
        with:
          # discord webhook id
          webhook_id: '856587514218545203'
          # discord webhook token
          webhook_token: 'OmVq23OAAKWh6VQGfoiFE-DRlGwtDst19OLHedR9HaQ7eONnVdlBJlc1i8OiAUpz4hqd'
          # the message contents (up to 2000 characters)
          message: |
          |
          Project 2- ${{ GITHUB.WORKFLOW }} 
          Build Number- ${{ GITHUB.RUN_NUMBER }} 
          Build Branch- ${{ GITHUB.REPOSITORY }} 
          Build Reason- ${{ GITHUB.EVENT_NAME }}
          # color code of the embed
          color: "#F3F910"
          # override the default username of the webhook
          username: "Team4-Webhooks"
          # override the default avatar of the webhook
          avatar_url: "https://i.pinimg.com/236x/da/df/6a/dadf6a20353342886904afc6af052b3a--for-cats-ironman.jpg"
