parameters:
  - name: 'displayName'
    type: string
  - name: 'targetPath'
    type: string
  - name: 'artifact'
    type: string
  - name: 'tags'
    type: string
  - name: 'Dockerfile'
    type: string
  - name: 'repository'
    type: string
  - name: 'stage'
    type: string

stages:
- stage: ${{ parameters.stage }}
  displayName: ${{ parameters.displayName }}
  dependsOn: Build_and_Test
  jobs:
  - job: BuildPushAzure
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: ${{ parameters.artifact }}
        itemPattern: '**.jar'
        targetPath: ${{ parameters.targetPath }}
    - task: Docker@2
      inputs:
        containerRegistry: 'team4-azure-containers'
        repository: 'team4containers'
        command: 'buildAndPush'
        Dockerfile: ${{ parameters.Dockerfile }}
        tags: ${{ parameters.tags }}

  - job: BuildPushDocker
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: ${{ parameters.artifact }}
        itemPattern: '**.jar'
        targetPath: './dockerize/'
    - task: Docker@2
      inputs:
        containerRegistry: 'team4-docker-containers'
        repository: ${{ parameters.repository }}
        command: 'buildAndPush'
        Dockerfile: ${{ parameters.Dockerfile }}
        tags: ${{ parameters.tags }}
        
  - template: ./discord-job-template.yml