# This pipeline will handle the CI/CD of a Flashcard Microservice associated with the project found:
# https://github.com/2105-may24-devops/project2-quiz-app

trigger:
  branches:
    include:
    - master

  paths:
    include:
    - flashcard-service
    exclude:
    - gateway-service
    - quiz-service
    - README.md

variables:
- name: service
  value: flashcard-service


stages:
- template: ./build-test-stage-template.yml
  parameters:
    mavenPomFile: "./$(service)/pom.xml"
    options: "-f $(service)/pom.xml"
    targetPath: "./$(service)/target/$(service)-0.0.1-SNAPSHOT.jar"
    artifact: $(service)
    displayName: '${{ variables.service }} Build and Test'

- template: ./docker-stage-template.yml
  parameters:
    stage: CommitImage
    displayName: '${{ variables.service }} Image Build and Push to ACR/Dockerhub'
    targetPath: './dockerize'
    Dockerfile: 'dockerize/flashcard.Dockerfile'
    artifact: $(service)
    tags: "$(service)-$(Build.SourceVersion)"
    repository: 'team4revops/$(service)'
- template: ./docker-stage-template.yml
  parameters:
    stage: LatestImage
    displayName: '${{ variables.service }} Image Build and Push to ACR/Dockerhub'
    targetPath: './dockerize'
    Dockerfile: 'dockerize/flashcard.Dockerfile'
    artifact: $(service)
    tags: latest
    repository: "team4revops/$(service)"
  
